Optimisation du calcul
Dibi-programming-language/Skribi-langage-source pull request #25
Opened 2023-03-28 17:31 UTC by PiggyPigCute

Oui il y a 4 `for` imbriqués, mais il parcours des tableaux tout petits

C'est peut-être encore optimisable

2023-03-29 08:18 UTC, Alexiscomete commented
C'est étrange de tout faire via des tokens. Les tokens normalement sont un symbole du code d'origine, pas une valeur. Je vais regarder.

2023-03-29 09:05 UTC, Alexiscomete requested changes
Très bonne ensemble. Désolé, mais je voit encore des modifications à faire 😅

2023-03-29 09:05 UTC, Alexiscomete commented on src/skribi/parser.py
> +
Très bien vu, mais dans ce cas à quoi sert l'offset ?

2023-03-29 10:48 UTC, PiggyPigCute commented on src/skribi/tokens.py
> +
Pas faux

2023-03-29 10:55 UTC, Alexiscomete commented on src/skribi/parser.py
> +
Etant donné que les opérations sont parcourus régulièrement, je pense que c'est au final moins optimisé

2023-03-29 10:55 UTC, PiggyPigCute commented on src/skribi/tokens.py
> +                    continue
C'est juste que tu avais créé un Token **NEWLINE**

Toi tu avais fait :
```
...
  if current_char.isspace():
    ...

  ... Une série de elif

  elif current_char == '\n':
    ...
    return Token(TT_NEWLINE, '\n')
  ...
```
Mais le cas
`current_char == '\n'` n'était jamais atteint

Et aussi, est-ce qu'on accepte cette syntaxe :
```
int
a = 5

if
(
a
<7){oste
(a
):
adatali}
```

2023-03-29 10:56 UTC, PiggyPigCute commented on src/skribi/program.py
> +        print(file.result.evaluate().display())
Je me doute

2023-03-29 10:56 UTC, Alexiscomete commented
J'ai fermé les conversations non obligatoires

2023-03-29 10:57 UTC, PiggyPigCute commented on src/skribi/parser.py
> +        op_locations = {0:[], 1:[], 2:[], 3:[]}
L'intérêt de ma nouvelle méthode, c'est que c'est vraiment simple d'ajouter un opérateur.

Mais oui, il faut l'ajouter

2023-03-29 10:57 UTC, Alexiscomete commented on src/skribi/tokens.py
> +                    continue
> Et aussi, est-ce qu'on accepte cette syntaxe :

C'est utile quand une fonction a de nombreux arguments, et l'appel chaîné

2023-03-29 10:58 UTC, PiggyPigCute commented on src/skribi/parser.py
> +        op_locations = {0:[], 1:[], 2:[], 3:[]}
D'ailleurs `and` et `or` sont des **OPERATORS** en fait

2023-03-29 10:59 UTC, Alexiscomete commented on src/skribi/parser.py
> +        op_locations = {0:[], 1:[], 2:[], 3:[]}
je ferme, on ajoutera plus tard

2023-03-29 11:01 UTC, PiggyPigCute commented on src/skribi/parser.py
>          while self.current_token.type in ["FLOAT", "INT", "OPERATOR"]:
Je n'ai pas compris où et quand est-ce que tu appelles la méthode `parse_math_expr`

2023-03-29 11:02 UTC, PiggyPigCute commented on src/skribi/parser.py
>          while self.current_token.type in ["FLOAT", "INT", "OPERATOR"]:
Donc, je sais pas

2023-03-29 11:03 UTC, PiggyPigCute commented on src/skribi/parser.py
> +        #  il décrémente de 2 tous les emplacements
(même avec les beaux commentaires ? 🥺 ^^)

Je t'explique sur Discord

2023-03-29 11:04 UTC, Alexiscomete commented on src/skribi/tokens.py
> +                    continue
j'ai enlevé

2023-03-29 11:05 UTC, PiggyPigCute commented on src/skribi/parser.py
> +                offset += 2
Je penses su'il faut tester ça au remplissage de `calc`

2023-03-29 11:05 UTC, Alexiscomete commented on src/skribi/parser.py
> +        #  il décrémente de 2 tous les emplacements
C'est bon j'ai compris, mais je vais essayer d'éclaircir pour les prochains

2023-03-29 11:06 UTC, Alexiscomete commented on src/skribi/parser.py
>          while self.current_token.type in ["FLOAT", "INT", "OPERATOR"]:
Bon temps pis, on s'en occupera plus tard

2023-03-29 11:09 UTC, PiggyPigCute commented on src/skribi/parser.py
> +
> Très bien vu, mais dans ce cas à quoi sert l'offset ?

Le offset, c'est pour le décalage dans la même priorité

Lorsque je parcours le tableau pour "noeudifier" les `*` et les `/`, j'utilise le `offset` pour décaler les `*` et les `/` suivants, et j'utilise boucles avec `k` et `l` poir décaler les `+`, `-`, `==`, `!=`...

2023-03-29 11:10 UTC, Alexiscomete commented on src/skribi/parser.py
> +
Hum ... ok

2023-03-29 11:12 UTC, PiggyPigCute commented on src/skribi/parser.py
> +        if self.token.value == '+':
Ah mais oui, on peut modifier ce que ça fait de faire Token+Token

2023-03-29 11:12 UTC, Alexiscomete commented on src/skribi/parser.py
> +        if self.token.value == '+':
Oui en effet

2023-03-29 11:13 UTC, Alexiscomete commented on src/skribi/parser.py
> +        if self.token.value == '+':
Mais ici on add leurs valeurs

2023-03-29 11:26 UTC, PiggyPigCute commented
> C'est étrange de tout faire via des tokens. Les tokens normalement sont un symbole du code d'origine, pas une valeur. Je vais regarder.

En fait, il faudrait faire deux classes différentes :

- La classe Token (ou `leksi` en dibi 👀) qui désigne un mot, un élément du code (opérateur, bracket, nombre, particule...)

- La classe Valeur, ou Instance (ou `coi` en dibi 👀) qui désigne l'instance d'une classe



Par exemple, si dans l'useur écrit

```
list toto = [1,2,3]
```

Le lexer (ou `leksifo` en dibi) analyserait 10 Tokens :
`list`, `toto`, `=`, `[`, `1`, `,`, `2`, `,`, `3` et `]`

Après, dans l'exécution du code, ça "attribuera" la valeur
```
Instance("list", [
    Instance("int", 1),
    Instance("int", 2),
    Instance("int", 3)
])
```

2023-03-29 11:32 UTC, PiggyPigCute commented on src/skribi/parser.py
> +        if self.token.value == '+':
Oui, logiquement un `OperatorNode` contient dans ses branches sois d'autres `OperatorNode`, dois des `Instance`

2023-03-29 11:33 UTC, PiggyPigCute commented on src/skribi/parser.py
> +        if self.token.value == '+':
Oui, logiquement un `OperatorNode` contient dans ses branches sois d'autres `OperatorNode`, dois des `Instance`

2023-03-29 11:43 UTC, PiggyPigCute commented
> Je viens de remarquer un bug : i+1 -> 3 n'inclue pas 3

Pas compris

2023-03-29 11:58 UTC, Alexiscomete commented
Ceux de priorités 3 ne sont jamais décalés de 2

2023-03-29 18:45 UTC, PiggyPigCute commented
> Ceux de priorités 3 ne sont jamais décalés de 2

Aaah, oui ok je vois
Oui car de base j'avais pas mis les comparaisons, faut mettre 4 dcp

2023-03-29 19:03 UTC, Alexiscomete commented
Il faut même mettre taille de priorité

2023-11-29 12:03 UTC, Alexiscomete commented
MINCE, j'avais oublié cette PR

2023-11-29 16:41 UTC, Alexiscomete commented
Close car passage en Rust

2023-11-29 16:41 UTC, closed without merging