Initialize rust repo
Dibi-programming-language/Skribi-langage-source pull request #26
Opened 2023-11-29 07:52 UTC by Rignchen

2023-11-29 11:19 UTC, Alexiscomete commented
Avant de faire quoi que ce soit je vais ajouter un tag sur le commit actuel afin de le retrouver facilement.

2023-11-29 16:57 UTC, Alexiscomete commented
Je fais une review puis j'arrête pour aujourd'hui, je dois bosser un peu.

2023-11-29 17:12 UTC, Alexiscomete requested changes
Très bon commit, cela pose de bonnes bases et permet de relancer le projet.
Je demande des changements avant le merge au niveau du .idea (voir mes commentaires).
En tout cas merci pour cette pr !
Je vais essayer de me plonger dans le Rust dès que possible afin d'aider au dev. Pour ce qui est des fichiers Rust, j'ai vite fais lu car je ne comprend pas grand chose au Rust pour le moment, mais cela me semble tout à fait correcte. Je vois même des éléments très bien pensés.

2023-11-29 17:12 UTC, Alexiscomete commented on .gitignore
> +*.pdb
```suggestion
*.pdb

# IDEs
.idea
```

2023-11-29 17:12 UTC, Alexiscomete commented on .idea/.gitignore
A supprimer

2023-11-29 17:12 UTC, Alexiscomete commented on Cargo.toml
> +edition = "2021"
```suggestion
name = "skribi_r"
version = "0.1.0"
edition = "2023"
```

2023-11-29 17:12 UTC, Alexiscomete commented on Cargo.toml
> +edition = "2021"
skribi r est une idée pour indiquer que c'est la version en Rust, à voir

2023-11-29 17:12 UTC, Alexiscomete commented on README.md
>  WARNING : please use this directory as the working directory, not 'src'.
La procédure devra être modifiée, le warning concernait python. Tout ceci on peut le faire dans une prochaine pr.

2023-11-30 12:28 UTC, Alexiscomete requested changes
Très bien

2023-11-30 20:49 UTC, Rignchen commented
Bah je sais pas comment faire pour t'y autoriser 🤔

2023-11-30 20:52 UTC, Rignchen commented on .gitignore
Intelij à son propre gitognore, il est donc utile de ne pas le mettre

2023-11-30 20:57 UTC, Alexiscomete commented on .idea/runConfigurations/Debug_skribi_interpret_.xml
A ma connaissance, le .idea est vraiment personnel donc pas à mettre sur git. Après je ne connais pas parfaitement le format.

2023-12-01 06:52 UTC, Alexiscomete approved these changes

2023-12-01 06:52 UTC, merged