Add native print and println and fix bugs on variables
Dibi-programming-language/Skribi-langage-source pull request #38
Opened 2023-12-26 18:08 UTC by Alexiscomete

close #33

2023-12-26 20:12 UTC, tatounee requested changes
Globalement correct, mais le code n'est pas idiomatique à Rust.
Deux remarques plus générales.
- Une pipeline avec Tokenizer -> Parser -> Interpreter permettrait d'avoir un code plus propre, plus lisible et plus flexible (la crate [Pest](https://crates.io/crates/pest) pourrait être une solution).
- La gestion des erreurs n'est PAS DU TOUT correcte et ressemble à un bricolage pour recréer des `throw`. À la place, il faut utiliser des `Option<T>`, des `Result<T, E>` et créer des erreurs customs avec le trait `str::error::Error`. L'utilisation de crates comme [anyhow](https://crates.io/crates/anyhow) ou [color-eyre](https://crates.io/crates/color-eyre) permet de gérer facilement les erreurs.

2023-12-26 20:43 UTC, Alexiscomete commented on src/pre_run.rs
Bien vu, j'avais pas vu.

2023-12-26 20:43 UTC, Alexiscomete commented on src/interpret/variables.rs
Je note tout ceci. Le format semble vraiment me simplifier l'utilisation des strings !! Est-ce que tu veux être mentionné après une fois tes changements appliqués ?

2023-12-26 20:43 UTC, Alexiscomete commented on src/interpret/variables.rs
Je vais me renseigner sur la différence entre &[...] et vec, pour le Clone j'avoue avoir suivi les conseils de ChatGPT car je débute vraiment en Rust.

2023-12-26 20:43 UTC, Alexiscomete commented on src/interpret/native_call.rs
En effet je vois. Pour ce qui est de l'enum, j'ai l'impression que je ne peux énumérer que des types donc bon ... je vais voir. Pour les valeurs possibles, ce sont de toute façon des valeurs qui ne devront pas être vu par l'utilisateur mais uniquement dans le code source de la lib principale du skribi. Mais cela n'empêche pas de mettre des vrais noms en effet.
Pour ce qui est de la création de la liste des arguments, est-ce qu'il est possible de faire mieux ?

2023-12-26 20:49 UTC, Alexiscomete commented
> Globalement correct, mais le code n'est pas idiomatique à Rust. Deux remarques plus générales.
> 
> * Une pipeline avec Tokenizer -> Parser -> Interpreter permettrait d'avoir un code plus propre, plus lisible et plus flexible (la crate [Pest](https://crates.io/crates/pest) pourrait être une solution).
> * La gestion des erreurs n'est PAS DU TOUT correcte et ressemble à un bricolage pour recréer des `throw`. À la place, il faut utiliser des `Option<T>`, des `Result<T, E>` et créer des erreurs customs avec le trait `str::error::Error`. L'utilisation de crates comme [anyhow](https://crates.io/crates/anyhow) ou [color-eyre](https://crates.io/crates/color-eyre) permet de gérer facilement les erreurs.

Pour la pipeline, c'était en grande partie prévue, mais pour commencer j'ai essayé de suivre ce qui avait été fait. Je regarderais la crate, même si le but était de faire la plus grande partie nous même afin d'apprendre au passage à coder tout ça. Mais c'est vrai que le Parser n'est jamais une étape facile (je redoute déjà).

Pour ce qui est des erreurs, je vais regarder. C'est vrai que se trimbaler le numéro de la ligne est vraiment chiant, et ce n'est rien par rapport à quand on aura un stack entier de scopes.

2023-12-29 18:07 UTC, tatounee approved these changes

2024-04-22 12:32 UTC, Alexiscomete commented
Certaines modifications sont en cours
Je me suis bien amélioré sur certains points cette année, et je vais retravailler certaines parties correctement

2024-05-28 16:54 UTC, closed without merging

2024-05-28 16:55 UTC, Alexiscomete commented
Outdated name and description. The content is very different.